// <auto-generated />
namespace PayPoint.WebApi.DbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class T1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(T1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410232244405_T1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
